---
layout: post
title: What Is Microsoft.Workflow.Compiler.exe  And Why Should You Disable It
date: '2018-11-08T12:00:00.001-08:00'
author: Matt C
tags: 
modified_time: '2019-08-21T07:16:18.630-07:00'
thumbnail: https://4.bp.blogspot.com/-wp858qkGegw/W-STi4YWzuI/AAAAAAAAANM/Q68SRTzqSbYRQJhx0VPp2Ks5xSVKNRysgCLcBGAs/s72-c/VT.png
blogger_id: tag:blogger.com,1999:blog-8951407132095927802.post-6530503358658328719
blogger_orig_url: https://cr.culbertreport.com/2018/11/what-is-microsoftworkflowcompilerexe.html
---

<b><u><span style="color: red;">What is it?</span></u></b><br />This is a built in function for C# in Microsoft Windows that essentially allows arbitrary unsigned code execution. It is part of the .NET framework and it works by combining a serialized workflow with an XML of serialized compiler arguments.<br /><br />Running this compiler on some C# code allows for a fileless payload and execution. In my test, this was used for a remote shell out from one computer to another.<br /><br /><span style="color: red;"><b><u>How does it affect me?</u></b></span><br />Users can easily download macro enabled Office documents that contain scripts designed to pull down the necessary source files and compile them into a working attack. Office macros have and always will be a huge attack vector, and disabling them outright is not an option in most cases.<br /><br />In my test case, I wrote a macro to create and execute a VBS file that pulls down all needed source files. I event went so far as to mask my requests with a Google URL which I described in a previous post. This would render it harder for outgoing connections to be determined malicious. The Office document in question only raised flags on 6 AV's and that was because they recognized the VBScript being created downloaded other files. However these were not industry recognized brands or brands you would find in most corporate environments.<br /><div class="separator" style="clear: both; text-align: center;"><a href="https://4.bp.blogspot.com/-wp858qkGegw/W-STi4YWzuI/AAAAAAAAANM/Q68SRTzqSbYRQJhx0VPp2Ks5xSVKNRysgCLcBGAs/s1600/VT.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" data-original-height="373" data-original-width="1079" height="110" src="https://4.bp.blogspot.com/-wp858qkGegw/W-STi4YWzuI/AAAAAAAAANM/Q68SRTzqSbYRQJhx0VPp2Ks5xSVKNRysgCLcBGAs/s320/VT.png" width="320" /></a></div><br /><br /><span style="color: red;"><b><u>Remediation</u></b></span><br />I recommend using Windows AppLocker to prevent the use of Microsoft.Workflow.Compiler.exe as well as preventing PowerShell from downloading files. This would stop most Office malware from executing, and most users do not have a good reason to be using the workflow compiler. See an example AppLocker policy below to restrict this.<br /><br /><ol><li>In Local Security Policy, expand Application Control Policies -&gt; AppLocker</li><li>Right click Executable Rules -&gt; Create New Rule</li><li>Select Deny and the user or group who it should be denied to</li><li>Since the Path of the file can be changed, select the File Hash option for blocking</li><li>Browse to the file in question, and add it</li><ol><li>It can be found at this location&nbsp;C:\Windows\Microsoft.Net\Framework64\v4.0.30319\Microsoft.Workflow.Compiler.exe</li></ol><li>Create!</li></ol>